-- local cmp = require('cmp')
-- local cmp_action = require('lsp-zero').cmp_action()
-- 
-- cmp.setup({
--     mapping = cmp.mapping.preset.insert({
--         -- `Enter` key to confirm completion
--         ['<CR>'] = cmp.mapping.confirm({ select = false }),
--         -- 'Tab' key to confirm completion
--         ['<Tab>'] = cmp.mapping.confirm({ select = false }),
--         -- Ctrl+Space to trigger completion menu
--         ['<C-Space>'] = cmp.mapping.complete(),
-- 
-- 
--         -- Scroll up and down in the completion documentation
--         ['<C-u>'] = cmp.mapping.scroll_docs(-4),
--         ['<C-d>'] = cmp.mapping.scroll_docs(4),
-- 
--         -- ['<Tab>'] = cmp_action.luasnip_supertab(),
--         -- ['<S-Tab>'] = cmp_action.luasnip_shift_supertab(),
--     }),
--     sources = cmp.config.sources({
--         { name = "nvim_lsp" }, -- LSP
--         { name = "luasnip" },  -- snippets
--         { name = "buffer" },   -- text within the current buffer
--         { name = "path" },     -- file system paths
--     }),
-- 
--     preselect = 'item',
--     completion = {
--         completeopt = 'menu,menuone,noinsert'
--     },
-- })
